on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup visual studio
        uses: microsoft/setup-msbuild@v2

      - name: Download LLVM installer for woa64
        run: |
          curl -L -o LLVM-woa64.exe https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.5/LLVM-19.1.5-woa64.exe
      
      - name: Install LLVM silently
        shell: pwsh
        run: |
          Start-Process -FilePath ".\LLVM-woa64.exe" -ArgumentList "/S" -Wait
      
      - name: Add LLVM to PATH
        shell: pwsh
        run: |
          $llvmPath = "C:\Program Files\LLVM\bin"
          echo "$llvmPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
      - name: Check clang and flang-new versions
        shell: pwsh
        run: |
          clang --version
          flang-new --version
